name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install xorg-dev
      run: sudo apt install -y xorg-dev
    - name: configure
      run: mkdir linux-build && cd linux-build && cmake ../ImSharp/ImSharp.OpenGL.Native
    - name: make
      run: make
